"""Added last message bool

Revision ID: 25cc24a1530f
Revises: 31392fa9a0c9
Create Date: 2024-07-09 13:49:37.871354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25cc24a1530f'
down_revision = '31392fa9a0c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_last_chat', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.drop_column('is_last_chat')

    # ### end Alembic commands ###
