"""Added like UNIQUE constraint.

Revision ID: 2dc61359c723
Revises: 0803c8b1f699
Create Date: 2024-07-08 20:23:45.658288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dc61359c723'
down_revision = '0803c8b1f699'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_likes', ['liker_id', 'liked_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.drop_constraint('unique_likes', type_='unique')

    # ### end Alembic commands ###
