"""Added default date

Revision ID: 30166ebb660e
Revises: 25cc24a1530f
Create Date: 2024-07-11 19:51:22.928178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30166ebb660e'
down_revision = '25cc24a1530f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('date_of_birth',
               existing_type=sa.DATE(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('date_of_birth',
               existing_type=sa.DATE(),
               nullable=True)

    # ### end Alembic commands ###
